apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: eshop
type: Opaque
data:
  username: ZXNob3B1c2Vy
  password: ZXNob3BwYXNzd29yZA==
  # Base64 encoded: eshopuser, eshoppassword

